# Generated by Django 3.1.10 on 2021-09-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0004_responsiveblogpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponsiveBlogPage',
        ),
    ]
