# Generated by Django 3.1.10 on 2021-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_responsiveblogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsiveblogpage',
            name='created',
            field=models.DateField(verbose_name='Date Article'),
        ),
    ]
