# Generated by Django 3.1.10 on 2021-09-14 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_stremblogpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StremBlogPage',
            new_name='StreamBlogPage',
        ),
    ]
